version: '3.7'
services:
  mysqld:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=youShouldChangeThis
      - MYSQL_ROOT_HOST=%
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3406:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  postgres:
    image: postgres:alpine3.19
    restart: always
    environment:
      - POSTGRES_DB=pgsql-saas
      - POSTGRES_USER=pgsql-saas
      - POSTGRES_PASSWORD=pgsql-saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  mysql_data:
  postgres_data: